package Daje::Plugin::Sentinel;
use Mojo::Base 'Mojolicious::Plugin', -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::Sentinel - Mojolicious Plugin
#
# SYNOPSIS
# ========
#
# Mojolicious
# ===========
#
#      $self->plugin('Sentinel');
#
# Mojolicious::Lite
# =================
#
#      plugin 'Sentinel';
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::Sentinel is a Mojolicious plugin.
#
# METHODS
# =======
#
# Daje::Plugin::Sentinel inherits all methods from
# Mojolicious::Plugin and implements the following new ones.
#
# register
# ========
#  $plugin->register(Mojolicious->new);
#
# Register plugin in L<Mojolicious> application.
#
# SEE ALSO
# ========
#
# Mojolicious, Mojolicious::Guides, https://mojolicious.org.
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated once automatically by Daje Tools 2026-01-04 14:30:12.
# It will not be touched by Daje Tools again.

# <!-- Autogenerated file 2026-01-04 14:30:12 -->

use Daje::Plugin::Sentinel::Routes;
use Daje::Plugin::Sentinel::Helpers;

our $VERSION = '0.01';

sub register ($self, $app, $config) {
    $app->log->debug("Daje::Plugin::Sentinel::register start");

    Daje::Plugin::Sentinel::Routes->new()->routes($app, $config);
    Daje::Plugin::Sentinel::Helpers->new()->helpers($app, $config);


    $app->log->debug("Daje::Plugin::Sentinel::register ends");
}

1;





























































































#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Plugin::Sentinel - Mojolicious Plugin



=head1 SYNOPSIS




=head1 DESCRIPTION


Daje::Plugin::Sentinel is a Mojolicious plugin.



=head1 REQUIRES

L<Daje::Plugin::Sentinel::Helpers> 

L<Daje::Plugin::Sentinel::Routes> 

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS


Daje::Plugin::Sentinel inherits all methods from
Mojolicious::Plugin and implements the following new ones.



=head1 Mojolicious


     $self->plugin('Sentinel');



=head1 register

 $plugin->register(Mojolicious->new);

Register plugin in L<Mojolicious> application.



=head1 Mojolicious::Lite


     plugin 'Sentinel';



=head1 SEE ALSO


Mojolicious, Mojolicious::Guides, https://mojolicious.org.



=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

