package Daje::Database::Model::Super::vSentinelSentinelActions;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vSentinelSentinelActions - Daje db model
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vSentinelSentinelActions;
#
#       my $table = Daje::Database::View::Super::vSentinelSentinelActions->new(db => $db);
#
#       my $result = $table->load_sentinel_sentinel_actions_pkey($self, $sentinel_sentinel_actions_pkey);
#
#       my $result = $table->load_sentinel_sentinel_fkey($self, $sentinel_sentinel_fkey);
##
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::vSentinelSentinelActions is a View super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-08 18:04:17.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-01-08 18:04:17 -->

our $VERSION = '0.01';

has 'fields' => '"sentinel_sentinel_actions_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","note",
"sentinel_sentinel_fkey"';
has 'primary_key_name' => "sentinel_sentinel_actions_pkey";
has 'table_name' => "v_sentinel_sentinel_actions";


async sub load_sentinel_sentinel_fkey_p($self, $sentinel_sentinel_fkey) {
    return $self->load_sentinel_sentinel_fkey($sentinel_sentinel_fkey);
}

sub load_sentinel_sentinel_fkey($self, $sentinel_sentinel_fkey) {
    return $self->load_fkey(
        $self->table_name, $self->fields(), "sentinel_sentinel_fkey", $sentinel_sentinel_fkey
    );
}
async sub load_sentinel_sentinel_actions_pkey_p($self, $sentinel_sentinel_actions_pkey) {
    return $self->load_sentinel_sentinel_actions_pkey($sentinel_sentinel_actions_pkey);
}

sub load_sentinel_sentinel_actions_pkey($self, $sentinel_sentinel_actions_pkey) {
    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $sentinel_sentinel_actions_pkey
    );
}

1;


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Database::View::Super::vSentinelSentinelActions - Daje db model



=head1 SYNOPSIS



      use Daje::Database::View::Super::vSentinelSentinelActions;

      my $table = Daje::Database::View::Super::vSentinelSentinelActions->new(db => $db);

      my $result = $table->load_sentinel_sentinel_actions_pkey($self, $sentinel_sentinel_actions_pkey);

      my $result = $table->load_sentinel_sentinel_fkey($self, $sentinel_sentinel_fkey);





=head1 DESCRIPTION


Daje::Database::View::Super::vSentinelSentinelActions is a View super class



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

