package Daje::Database::View::Super::vSentinelSentinelActionsList;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vSentinelSentinelActionsList - Daje db view
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vSentinelSentinelActionsList;
#
#       my $table = Daje::Database::View::Super::vSentinelSentinelActionsList->new(db => $db);
#
#       my $result = $table->load_sentinel_sentinel_actions_pkey($self, $sentinel_sentinel_actions_pkey);
#
#       my $result = $table->load_sentinel_sentinel_fkey($self, $sentinel_sentinel_fkey);
##
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::Model::Super::SentinelSentinelActionsList is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-11 13:16:15.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-01-11 13:16:15 -->

our $VERSION = '0.01';

has 'fields' => '"sentinel_sentinel_actions_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime","note",
"sentinel_sentinel_fkey"';
has 'primary_key_name' => "sentinel_sentinel_actions_pkey";
has 'table_name' => "v_sentinel_sentinel_actions_list";

async sub load_all_sentinel_sentinel_list_p($self) {
    return $self->load_all_sentinel_sentinel_list();
}

sub load_all_sentinel_sentinel_list($self) {
    return $self->load_a_full_list(
        $self->table_name, $self->fields()
    );
}

async sub load_sentinel_sentinel_list_p($self, $key_value) {
    return $self->load_sentinel_sentinel_list($key_value);
}

sub load_sentinel_sentinel_list($self, $key_value) {
    return $self->load_a_list(
        $self->table_name, $self->fields(), $key_value
    );
}

async sub load_sentinel_sentinel_actions_pkey_p($self, $sentinel_sentinel_actions_pkey) {
    return $self->load_sentinel_sentinel_actions_pkey($sentinel_sentinel_actions_pkey);
}

sub load_sentinel_sentinel_actions_pkey($self, $sentinel_sentinel_actions_pkey) {
    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $sentinel_sentinel_actions_pkey
    );
}
1;



#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Database::View::Super::vSentinelSentinelActionsList - Daje db view



=head1 SYNOPSIS



      use Daje::Database::View::Super::vSentinelSentinelActionsList;

      my $table = Daje::Database::View::Super::vSentinelSentinelActionsList->new(db => $db);

      my $result = $table->load_sentinel_sentinel_actions_pkey($self, $sentinel_sentinel_actions_pkey);

      my $result = $table->load_sentinel_sentinel_fkey($self, $sentinel_sentinel_fkey);

      my $result = $table->insert($self, $data);

      $table->update($self, $data) ;




=head1 DESCRIPTION


Daje::Database::Model::Super::SentinelSentinelActionsList is a Model super class



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

