package Daje::Database::View::Super::vSentinelCheckpointLog;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::View::Super::vSentinelCheckpointLog - Daje db model
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::View::Super::vSentinelCheckpointLog;
#
#       my $table = Daje::Database::View::Super::vSentinelCheckpointLog->new(db => $db);
#
#       my $result = $table->load_sentinel_checkpoint_log_pkey($self, $sentinel_checkpoint_log_pkey);
#
#       my $result = $table->load_sentinel_checkpoint_fkey($self, $sentinel_checkpoint_fkey);
##
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::View::Super::vSentinelCheckpointLog is a View super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-18 15:11:43.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-01-18 15:11:43 -->

our $VERSION = '0.01';

has 'fields' => '"sentinel_checkpoint_log_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime",
"sentinel_checkpoint_fkey","lastexecution"';
has 'primary_key_name' => "sentinel_checkpoint_log_pkey";
has 'table_name' => "v_sentinel_checkpoint_log";


async sub load_sentinel_checkpoint_fkey_p($self, $sentinel_checkpoint_fkey) {
    return $self->load_sentinel_checkpoint_fkey($sentinel_checkpoint_fkey);
}

sub load_sentinel_checkpoint_fkey($self, $sentinel_checkpoint_fkey) {
    return $self->load_fkey(
        $self->table_name, $self->fields(), "sentinel_checkpoint_fkey", $sentinel_checkpoint_fkey
    );
}
async sub load_sentinel_checkpoint_log_pkey_p($self, $sentinel_checkpoint_log_pkey) {
    return $self->load_sentinel_checkpoint_log_pkey($sentinel_checkpoint_log_pkey);
}

sub load_sentinel_checkpoint_log_pkey($self, $sentinel_checkpoint_log_pkey) {
    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $sentinel_checkpoint_log_pkey
    );
}

1;





#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Database::View::Super::vSentinelCheckpointLog - Daje db model



=head1 SYNOPSIS



      use Daje::Database::View::Super::vSentinelCheckpointLog;

      my $table = Daje::Database::View::Super::vSentinelCheckpointLog->new(db => $db);

      my $result = $table->load_sentinel_checkpoint_log_pkey($self, $sentinel_checkpoint_log_pkey);

      my $result = $table->load_sentinel_checkpoint_fkey($self, $sentinel_checkpoint_fkey);





=head1 DESCRIPTION


Daje::Database::View::Super::vSentinelCheckpointLog is a View super class



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

