package Daje::Database::Model::Super::SentinelCheckpointLog;
use Mojo::Base 'Daje::Database::Model::Super::Common::Base', -base, -signatures, -async_await;
use v5.42;

# NAME
# ====
#
# Daje::Database::Model::Super::SentinelCheckpointLog - Daje db model
#
# SYNOPSIS
# ========
#
#
#       use Daje::Database::Model::Super::SentinelCheckpointLog;
#
#       my $table = Daje::Database::Model::Super::SentinelCheckpointLog->new(db => $db);
#
#       my $result = $table->load_sentinel_checkpoint_log_pkey($self, $sentinel_checkpoint_log_pkey);
#
#       my $result = $table->load_sentinel_checkpoint_fkey($self, $sentinel_checkpoint_fkey);
##
#       my $result = $table->insert($self, $data);
#
#       $table->update($self, $data) ;
#
#
# DESCRIPTION
# ===========
#
# Daje::Database::Model::Super::SentinelCheckpointLog is a Model super class
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-08 18:04:17.
# It will be re-created by Daje Tools again and any changes
# will be over written.
#
# <!-- Autogenerated file 2026-01-08 18:04:17 -->

our $VERSION = '0.01';

has 'fields' => '"sentinel_checkpoint_log_pkey", "editnum", "insby", "insdatetime", "modby", "moddatetime",
"sentinel_checkpoint_fkey","lastexecution"';
has 'primary_key_name' => "sentinel_checkpoint_log_pkey";
has 'table_name' => "sentinel_checkpoint_log";
has 'mandatory' => '';

async sub load_sentinel_checkpoint_fkey_p($self, $sentinel_checkpoint_fkey) {
    return $self->load_sentinel_checkpoint_fkey($sentinel_checkpoint_fkey);
}

sub load_sentinel_checkpoint_fkey($self, $sentinel_checkpoint_fkey) {
    return $self->load_fkey(
        $self->table_name, $self->fields(), "sentinel_checkpoint_fkey", $sentinel_checkpoint_fkey
    );
}
async sub load_sentinel_checkpoint_log_pkey_p($self, $sentinel_checkpoint_log_pkey) {
    return $self->load_sentinel_checkpoint_log_pkey($sentinel_checkpoint_log_pkey);
}

sub load_sentinel_checkpoint_log_pkey($self, $sentinel_checkpoint_log_pkey) {
    return $self->load_pk(
        $self->table_name, $self->fields(), $self->primary_key_name(), $sentinel_checkpoint_log_pkey
    );
}

sub insert($self, $data) {
    my $result = $self->SUPER::insert(
        $self->table_name, $data, $self->primary_key_name
    );
    return $result;
}

sub update($self, $data) {
    return $self->SUPER::update
    (
        $self->table_name, $data,
            {
                $self->primary_key_name() => $data->{$self->primary_key_name()}
            }
    );
}

sub delete($self, $data) {
    return $self->SUPER::delete(
        $self->table_name,
            {
                $self->primary_key_name() => $data->{$self->primary_key_name()}
            }
     );
}
1;


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Database::Model::Super::SentinelCheckpointLog - Daje db model



=head1 SYNOPSIS



      use Daje::Database::Model::Super::SentinelCheckpointLog;

      my $table = Daje::Database::Model::Super::SentinelCheckpointLog->new(db => $db);

      my $result = $table->load_sentinel_checkpoint_log_pkey($self, $sentinel_checkpoint_log_pkey);

      my $result = $table->load_sentinel_checkpoint_fkey($self, $sentinel_checkpoint_fkey);

      my $result = $table->insert($self, $data);

      $table->update($self, $data) ;




=head1 DESCRIPTION


Daje::Database::Model::Super::SentinelCheckpointLog is a Model super class



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

