package Daje::Controller::Super::SentinelSentinelActionsList;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Super::SentinelSentinelActionsList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Super::vSentinelSentinelActions##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Super::SentinelSentinelActions is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-01-16 07:04:49.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-16 07:04:49 -->

our $VERSION = '0.01';

sub load_all_sentinel_sentinel_actions($self) {
    $self->app->log->debug('Daje::Controller::Super::SentinelSentinelActionsList::load_all_sentinel_sentinel_actions ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_sentinel_sentinel_actions_list->load_all_sentinel_sentinel_actions_p()->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::SentinelSentinelActionsList::load_all_sentinel_sentinel_actions ' . $err);
        $self->render
    });
}
sub load_list_sentinel_sentinel_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::SentinelSentinelActionsList::load_listsentinel_sentinel_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('sentinel_sentinel_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_sentinel__list->sentinel_sentinel_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::SentinelSentinelActions::load_sentinel_sentinel_fkey ' . $err);
        $self->render
    });
}
1;


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Controller::Super::SentinelSentinelActionsList - Model class



=head1 SYNOPSIS


      use Daje::Controller::Super::vSentinelSentinelActions##



=head1 DESCRIPTION


Daje::Controller::Super::SentinelSentinelActions is a standard controller



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com

This file is generated automatically by Daje Tools 2026-01-16 07:04:49.
It will be re-generated by Daje Tools again.
<!-- Autogenerated file 2026-01-16 07:04:49 -->


=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

