package Daje::Controller::Super::vSentinelStatusList;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Super::SentinelStatusList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Super::vSentinelStatus##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Super::SentinelStatus is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-01-09 04:53:43.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-09 04:53:43 -->

our $VERSION = '0.01';

sub load_all_sentinel_status($self) {
    $self->app->log->debug('Daje::Controller::Super::vSentinelStatus::load_sentinel__fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->sentinel_status->load_all_sentinel_status_pkey_p($pkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::vSentinelStatusList::load_all_sentinel_status_pkey ' . $err);
        $self->render
    });
}

1;


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Controller::Super::SentinelStatusList - Model class



=head1 SYNOPSIS


      use Daje::Controller::Super::vSentinelStatus##



=head1 DESCRIPTION


Daje::Controller::Super::SentinelStatus is a standard controller



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com

This file is generated automatically by Daje Tools 2026-01-09 04:53:43.
It will be re-generated by Daje Tools again.
<!-- Autogenerated file 2026-01-09 04:53:43 -->


=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

