__DATA__

@@ sentinel

use Daje::Database::Sentinel
use Mojo::Base -base
use v5.42;



-- Autogenerated file, any changes to this file will be over written.
-- Last generated 2026-01-04 17:14:12


-- up 1
    
CREATE TABLE IF NOT EXISTS sentinel_status
(
    sentinel_status_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                status  VARCHAR  UNIQUE  NOT NULL DEFAULT '' ,
                CONSTRAINT sentinel_status_pkey PRIMARY KEY (sentinel_status_pkey)
);
    
CREATE TABLE IF NOT EXISTS sentinel_sentinel
(
    sentinel_sentinel_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                closed  BOOLEAN  NOT NULL DEFAULT false ,
                        recipients  VARCHAR  NOT NULL DEFAULT '' ,
                        ticket  BIGINT  NOT NULL DEFAULT 0 ,
                        source  VARCHAR  NOT NULL DEFAULT '' ,
                        method  VARCHAR  NOT NULL DEFAULT '' ,
                        message  VARCHAR  NOT NULL DEFAULT '' ,
                    sentinel_status_fkey BIGINT NOT NULL,
                CONSTRAINT sentinel_sentinel_pkey PRIMARY KEY (sentinel_sentinel_pkey)
);
    
CREATE TABLE IF NOT EXISTS sentinel_checkpoint
(
    sentinel_checkpoint_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            sentinel_interface_fkey BIGINT NOT NULL,
                        checkpoint  VARCHAR  NOT NULL DEFAULT '' ,
                        checkpoint_name  VARCHAR  UNIQUE  NOT NULL ,
                        intervall  BIGINT  NOT NULL DEFAULT 0 ,
                        credentials  VARCHAR ,
                        nextexecution  TIMESTAMP  NOT NULL DEFAULT NOW() ,
                CONSTRAINT sentinel_checkpoint_pkey PRIMARY KEY (sentinel_checkpoint_pkey)
);
    
CREATE TABLE IF NOT EXISTS sentinel_interface
(
    sentinel_interface_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                interface  VARCHAR  NOT NULL ,
                        interface_name  VARCHAR  UNIQUE  NOT NULL ,
                CONSTRAINT sentinel_interface_pkey PRIMARY KEY (sentinel_interface_pkey)
);
    
CREATE TABLE IF NOT EXISTS sentinel_checkpoint_log
(
    sentinel_checkpoint_log_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            sentinel_checkpoint_fkey BIGINT NOT NULL,
                        lastexecution  TIMESTAMP  NOT NULL ,
                CONSTRAINT sentinel_checkpoint_log_pkey PRIMARY KEY (sentinel_checkpoint_log_pkey)
);
    
CREATE TABLE IF NOT EXISTS sentinel_sentinel_actions
(
    sentinel_sentinel_actions_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                note  VARCHAR  NOT NULL DEFAULT '' ,
                    sentinel_sentinel_fkey BIGINT NOT NULL,
                CONSTRAINT sentinel_sentinel_actions_pkey PRIMARY KEY (sentinel_sentinel_actions_pkey)
);
    

CREATE OR REPLACE VIEW v_sentinel_status AS
    SELECT sentinel_status_pkey, editnum, insby, insdatetime, modby, moddatetime, status
          FROM sentinel_status;

CREATE OR REPLACE VIEW v_sentinel_sentinel AS
    SELECT sentinel_sentinel_pkey, editnum, insby, insdatetime, modby, moddatetime, closed,
      recipients,
      ticket,
      source,
      method,
      message,
     sentinel_status_fkey
          FROM sentinel_sentinel;

CREATE OR REPLACE VIEW v_sentinel_checkpoint AS
    SELECT sentinel_checkpoint_pkey, editnum, insby, insdatetime, modby, moddatetime,sentinel_interface_fkey,
      checkpoint,
      checkpoint_name,
      intervall,
      credentials,
      nextexecution
          FROM sentinel_checkpoint;

CREATE OR REPLACE VIEW v_sentinel_interface AS
    SELECT sentinel_interface_pkey, editnum, insby, insdatetime, modby, moddatetime, interface,
      interface_name
          FROM sentinel_interface;

CREATE OR REPLACE VIEW v_sentinel_checkpoint_log AS
    SELECT sentinel_checkpoint_log_pkey, editnum, insby, insdatetime, modby, moddatetime,sentinel_checkpoint_fkey,
      lastexecution
          FROM sentinel_checkpoint_log;

CREATE OR REPLACE VIEW v_sentinel_sentinel_actions AS
    SELECT sentinel_sentinel_actions_pkey, editnum, insby, insdatetime, modby, moddatetime, note,
     sentinel_sentinel_fkey
          FROM sentinel_sentinel_actions;



-- Insert statuses for sentinel tickets
INSERT INTO sentinel_status (status) 
VALUES ('New'), ('Ticket'), ('Closed'); 

                ALTER TABLE sentinel_sentinel
    ADD CONSTRAINT sentinel_sentinel_sentinel_status_fkey
FOREIGN KEY (sentinel_status_fkey)
    REFERENCES sentinel_status (sentinel_status_pkey);

CREATE INDEX ind_sentinel_sentinel_status_fkey
    ON sentinel_sentinel(sentinel_status_fkey);
      ALTER TABLE sentinel_checkpoint
    ADD CONSTRAINT sentinel_checkpoint_sentinel_interface_fkey
FOREIGN KEY (sentinel_interface_fkey)
    REFERENCES sentinel_interface (sentinel_interface_pkey);

CREATE INDEX ind_sentinel_checkpoint_interface_fkey
    ON sentinel_checkpoint(sentinel_interface_fkey);
                      ALTER TABLE sentinel_checkpoint_log
    ADD CONSTRAINT sentinel_checkpoint_log_sentinel_checkpoint_fkey
FOREIGN KEY (sentinel_checkpoint_fkey)
    REFERENCES sentinel_checkpoint (sentinel_checkpoint_pkey);

CREATE INDEX ind_sentinel_checkpoint_log_checkpoint_fkey
    ON sentinel_checkpoint_log(sentinel_checkpoint_fkey);
          ALTER TABLE sentinel_sentinel_actions
    ADD CONSTRAINT sentinel_sentinel_actions_sentinel_sentinel_fkey
FOREIGN KEY (sentinel_sentinel_fkey)
    REFERENCES sentinel_sentinel (sentinel_sentinel_pkey);

CREATE INDEX ind_sentinel_sentinel_actions_sentinel_fkey
    ON sentinel_sentinel_actions(sentinel_sentinel_fkey);
      
-- down 1




#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

::home::jan::Project::Daje-Plugin-Sentinel::lib::Daje::Database::Sentinel - ::home::jan::Project::Daje-Plugin-Sentinel::lib::Daje::Database::Sentinel


=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS


=cut

