package Daje::Database::Sentinel;
use Mojo::Base -base;
use v5.42;

our $VERSION = '1';

1;

__DATA__

@@ sentinel

-- 1 up

-- Autogenerated file, any changes to this file will be over written.
-- Last generated 2026-01-21 18:15:58

    
CREATE TABLE IF NOT EXISTS sentinel_sentinel_actions
(
    sentinel_sentinel_actions_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                note  VARCHAR  NOT NULL DEFAULT '' ,
                    sentinel_sentinel_fkey BIGINT NOT NULL,
                CONSTRAINT sentinel_sentinel_actions_pkey PRIMARY KEY (sentinel_sentinel_actions_pkey)
);
    
CREATE TABLE IF NOT EXISTS sentinel_status
(
    sentinel_status_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                status  VARCHAR  UNIQUE  NOT NULL DEFAULT '' ,
                    sentinel_workflow_fkey BIGINT NOT NULL,
                CONSTRAINT sentinel_status_pkey PRIMARY KEY (sentinel_status_pkey)
);
    
CREATE TABLE IF NOT EXISTS sentinel_interface
(
    sentinel_interface_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                interface  VARCHAR  NOT NULL ,
                        interface_name  VARCHAR  UNIQUE  NOT NULL ,
                    sentinel_workflow_fkey BIGINT NOT NULL,
                CONSTRAINT sentinel_interface_pkey PRIMARY KEY (sentinel_interface_pkey)
);
    
CREATE TABLE IF NOT EXISTS sentinel_checkpoint
(
    sentinel_checkpoint_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                checkpoint  VARCHAR  NOT NULL DEFAULT '' ,
                        checkpoint_name  VARCHAR  UNIQUE  NOT NULL ,
                        intervall  BIGINT  NOT NULL DEFAULT 0 ,
                        credentials  VARCHAR ,
                        nextexecution  TIMESTAMP  NOT NULL DEFAULT NOW() ,
                    sentinel_interface_fkey BIGINT NOT NULL,
                        active  BOOLEAN  NOT NULL DEFAULT false ,
                    sentinel_workflow_fkey BIGINT NOT NULL,
                CONSTRAINT sentinel_checkpoint_pkey PRIMARY KEY (sentinel_checkpoint_pkey)
);
    
CREATE TABLE IF NOT EXISTS sentinel_checkpoints
(
    sentinel_checkpoints_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
            sentinel_workflow_fkey BIGINT NOT NULL,
                    sentinel_checkpoint_fkey BIGINT NOT NULL,
                        lastexecution  TIMESTAMP  NOT NULL ,
                CONSTRAINT sentinel_checkpoints_pkey PRIMARY KEY (sentinel_checkpoints_pkey)
);
    
CREATE TABLE IF NOT EXISTS sentinel_sentinel
(
    sentinel_sentinel_pkey  SERIAL NOT NULL,
    editnum bigint NOT NULL DEFAULT 1,
    insby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    insdatetime timestamp without time zone NOT NULL DEFAULT now(),
    modby character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'System'::character varying,
    moddatetime timestamp without time zone NOT NULL DEFAULT now(),
                message  VARCHAR  NOT NULL DEFAULT '' ,
                        method  VARCHAR  NOT NULL DEFAULT '' ,
                        source  VARCHAR  NOT NULL DEFAULT '' ,
                    sentinel_status_fkey BIGINT NOT NULL,
                    sentinel_workflow_fkey BIGINT NOT NULL,
                        ticket  BIGINT  NOT NULL DEFAULT 0 ,
                CONSTRAINT sentinel_sentinel_pkey PRIMARY KEY (sentinel_sentinel_pkey)
);
    

CREATE OR REPLACE VIEW v_sentinel_sentinel_actions AS
    SELECT sentinel_sentinel_actions_pkey, editnum, insby, insdatetime, modby, moddatetime, note,
     sentinel_sentinel_fkey
          FROM sentinel_sentinel_actions;
CREATE OR REPLACE VIEW v_sentinel_status AS
    SELECT sentinel_status_pkey, editnum, insby, insdatetime, modby, moddatetime, status,
     sentinel_workflow_fkey
          FROM sentinel_status;
CREATE OR REPLACE VIEW v_sentinel_interface AS
    SELECT sentinel_interface_pkey, editnum, insby, insdatetime, modby, moddatetime, interface,
      interface_name,
     sentinel_workflow_fkey
          FROM sentinel_interface;
CREATE OR REPLACE VIEW v_sentinel_checkpoint AS
    SELECT sentinel_checkpoint_pkey, editnum, insby, insdatetime, modby, moddatetime, checkpoint,
      checkpoint_name,
      intervall,
      credentials,
      nextexecution,
     sentinel_interface_fkey,
      active,
     sentinel_workflow_fkey
          FROM sentinel_checkpoint;
CREATE OR REPLACE VIEW v_sentinel_checkpoints AS
    SELECT sentinel_checkpoints_pkey, editnum, insby, insdatetime, modby, moddatetime,sentinel_workflow_fkey,
     sentinel_checkpoint_fkey,
      lastexecution
          FROM sentinel_checkpoints;
CREATE OR REPLACE VIEW v_sentinel_sentinel AS
    SELECT sentinel_sentinel_pkey, editnum, insby, insdatetime, modby, moddatetime, message,
      method,
      source,
     sentinel_status_fkey,
     sentinel_workflow_fkey,
      ticket
          FROM sentinel_sentinel;


CREATE OR REPLACE VIEW v_sentinel_sentinel_actions_list AS
    SELECT sentinel_sentinel_actions_pkey, editnum, insby, insdatetime, modby, moddatetime, note,sentinel_sentinel_fkey     FROM sentinel_sentinel_actions;

CREATE OR REPLACE VIEW v_sentinel_status_list AS
    SELECT sentinel_status_pkey, editnum, insby, insdatetime, modby, moddatetime, status,sentinel_workflow_fkey     FROM sentinel_status;

CREATE OR REPLACE VIEW v_sentinel_interface_list AS
    SELECT sentinel_interface_pkey, editnum, insby, insdatetime, modby, moddatetime, interface, interface_name,sentinel_workflow_fkey     FROM sentinel_interface;

CREATE OR REPLACE VIEW v_sentinel_checkpoint_list AS
    SELECT sentinel_checkpoint_pkey, editnum, insby, insdatetime, modby, moddatetime, checkpoint, checkpoint_name, intervall, credentials, nextexecution,     (SELECT interface_name FROM sentinel_interface WHERE sentinel_interface_pkey = sentinel_interface_fkey) as sentinel_interface_interface_name,sentinel_interface_fkey, active,sentinel_workflow_fkey     FROM sentinel_checkpoint;

CREATE OR REPLACE VIEW v_sentinel_checkpoints_list AS
    SELECT sentinel_checkpoints_pkey, editnum, insby, insdatetime, modby, moddatetime,sentinel_workflow_fkey,sentinel_checkpoint_fkey, lastexecution     FROM sentinel_checkpoints;

CREATE OR REPLACE VIEW v_sentinel_sentinel_list AS
    SELECT sentinel_sentinel_pkey, editnum, insby, insdatetime, modby, moddatetime, message, method, source,     (SELECT status FROM sentinel_status WHERE sentinel_status_pkey = sentinel_status_fkey) as sentinel_status_status,sentinel_status_fkey,sentinel_workflow_fkey, ticket     FROM sentinel_sentinel;





  ALTER TABLE sentinel_sentinel_actions
    ADD CONSTRAINT sentinel_sentinel_actions_sentinel_sentinel_fkey
FOREIGN KEY (sentinel_sentinel_fkey)
    REFERENCES sentinel_sentinel (sentinel_sentinel_pkey);


CREATE INDEX ind_sentinel_sentinel_actions_sentinel_fkey
    ON sentinel_sentinel_actions(sentinel_sentinel_fkey);
  
    
  ALTER TABLE sentinel_status
    ADD CONSTRAINT sentinel_status_sentinel_workflow_fkey
FOREIGN KEY (sentinel_workflow_fkey)
    REFERENCES workflow (workflow_pkey);

CREATE INDEX ind_sentinel_status_workflow_fkey
    ON sentinel_status(sentinel_workflow_fkey);
  
    
  
  ALTER TABLE sentinel_interface
    ADD CONSTRAINT sentinel_interface_sentinel_workflow_fkey
FOREIGN KEY (sentinel_workflow_fkey)
    REFERENCES workflow (workflow_pkey);

CREATE INDEX ind_sentinel_interface_workflow_fkey
    ON sentinel_interface(sentinel_workflow_fkey);
  
    
  
  
  
  
  ALTER TABLE sentinel_checkpoint
    ADD CONSTRAINT sentinel_checkpoint_sentinel_interface_fkey
FOREIGN KEY (sentinel_interface_fkey)
    REFERENCES sentinel_interface (sentinel_interface_pkey);


CREATE INDEX ind_sentinel_checkpoint_interface_fkey
    ON sentinel_checkpoint(sentinel_interface_fkey);
  
  
  ALTER TABLE sentinel_checkpoint
    ADD CONSTRAINT sentinel_checkpoint_sentinel_workflow_fkey
FOREIGN KEY (sentinel_workflow_fkey)
    REFERENCES workflow (workflow_pkey);

CREATE INDEX ind_sentinel_checkpoint_workflow_fkey
    ON sentinel_checkpoint(sentinel_workflow_fkey);
  
    ALTER TABLE sentinel_checkpoints
    ADD CONSTRAINT sentinel_checkpoints_sentinel_workflow_fkey
FOREIGN KEY (sentinel_workflow_fkey)
    REFERENCES workflow (workflow_pkey);

CREATE INDEX ind_sentinel_checkpoints_workflow_fkey
    ON sentinel_checkpoints(sentinel_workflow_fkey);
  
  ALTER TABLE sentinel_checkpoints
    ADD CONSTRAINT sentinel_checkpoints_sentinel_checkpoint_fkey
FOREIGN KEY (sentinel_checkpoint_fkey)
    REFERENCES sentinel_checkpoint (sentinel_checkpoint_pkey);


CREATE INDEX ind_sentinel_checkpoints_checkpoint_fkey
    ON sentinel_checkpoints(sentinel_checkpoint_fkey);
  
  
    
  
  
  ALTER TABLE sentinel_sentinel
    ADD CONSTRAINT sentinel_sentinel_sentinel_status_fkey
FOREIGN KEY (sentinel_status_fkey)
    REFERENCES sentinel_status (sentinel_status_pkey);


CREATE INDEX ind_sentinel_sentinel_status_fkey
    ON sentinel_sentinel(sentinel_status_fkey);
  
  ALTER TABLE sentinel_sentinel
    ADD CONSTRAINT sentinel_sentinel_sentinel_workflow_fkey
FOREIGN KEY (sentinel_workflow_fkey)
    REFERENCES workflow (workflow_pkey);

CREATE INDEX ind_sentinel_sentinel_workflow_fkey
    ON sentinel_sentinel(sentinel_workflow_fkey);
  
  
    
-- 1 down



@@ the_end


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME

Daje::Database::Sentinel


=head1 DESCRIPTION

pod generated by Pod::Autopod - keep this line to make pod updates possible ####################


=head1 REQUIRES

L<Daje::Templates::Tools::Generate::SQL> 

L<Daje::Templates::Tools::Generate::SQL> 

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS

=head2 length_default_calc($self)

 length_default_calc($self)();


=cut

