package Daje::Plugin::Sentinel::Authorities;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::Sentinel::Authorities - Model class
#
# SYNOPSIS
# ========
#
#
#
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::Sentinel::Authorities is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-02-14 15:49:01.
# It will be generated by Daje Tools again.
# <!-- Autogenerated file 2026-02-14 15:49:01 -->

use Daje::Helper::Authorities::InsertPluginFunction;

has 'db';

sub authorize($self) {

    try {
        my $tx = $self->db->begin;
        my @functions = (
            "sentinel_sentinel_actions",
            "sentinel_interface",
            "sentinel_checkpoint",
            "sentinel_checkpoints",
            "sentinel_sentinel",
            "sentinel_status"
        );

        Daje::Helper::Authorities::InsertPluginFunction->new(
            db => $self->db
        )->process(
            "sentinel", \@functions
        );
        $tx->commit();
    } catch($e) {
        say $e;
    }
}

1;














































































































































































































#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Plugin::Sentinel::Authorities - Model class



=head1 SYNOPSIS







=head1 DESCRIPTION


Daje::Plugin::Sentinel::Authorities is the standard routes



=head1 REQUIRES

L<Daje::Helper::Authorities::InsertPluginFunction> 

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

