package Daje::Plugin::Sentinel::Helpers;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::Sentinel::Helpers - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Plugin::Sentinel::Helpers;
#
#       my $class = Daje::Plugin::Sentinel::Helpers->new();
#       $app->helper(
#           v_sentinel_status => sub {
#               state  $v_sentinel_status = Daje::Database::Model::vSentinelStatus->new(db => shift->pg->db)
#        });
#       $app->helper(
#           v_sentinel_sentinel => sub {
#               state  $v_sentinel_sentinel = Daje::Database::Model::vSentinelSentinel->new(db => shift->pg->db)
#        });
#       $app->helper(
#           v_sentinel_checkpoint_log => sub {
#               state  $v_sentinel_checkpoint_log = Daje::Database::Model::vSentinelCheckpointLog->new(db => shift->pg->db)
#        });
#       $app->helper(
#           v_sentinel_sentinel_actions => sub {
#               state  $v_sentinel_sentinel_actions = Daje::Database::Model::vSentinelSentinelActions->new(db => shift->pg->db)
#        });
#       $app->helper(
#           v_sentinel_checkpoint => sub {
#               state  $v_sentinel_checkpoint = Daje::Database::Model::vSentinelCheckpoint->new(db => shift->pg->db)
#        });
#       $app->helper(
#           v_sentinel_interface => sub {
#               state  $v_sentinel_interface = Daje::Database::Model::vSentinelInterface->new(db => shift->pg->db)
#        });#
#       $app->helper(
#           v_sentinel_status_list => sub {
#               state  $v_sentinel_status_list = Daje::Database::Model::vSentinelStatusList->new(db => shift->pg->db)
#        });
#       $app->helper(
#           v_sentinel_sentinel_list => sub {
#               state  $v_sentinel_sentinel_list = Daje::Database::Model::vSentinelSentinelList->new(db => shift->pg->db)
#        });
#       $app->helper(
#           v_sentinel_checkpoint_log_list => sub {
#               state  $v_sentinel_checkpoint_log_list = Daje::Database::Model::vSentinelCheckpointLogList->new(db => shift->pg->db)
#        });
#       $app->helper(
#           v_sentinel_sentinel_actions_list => sub {
#               state  $v_sentinel_sentinel_actions_list = Daje::Database::Model::vSentinelSentinelActionsList->new(db => shift->pg->db)
#        });
#       $app->helper(
#           v_sentinel_checkpoint_list => sub {
#               state  $v_sentinel_checkpoint_list = Daje::Database::Model::vSentinelCheckpointList->new(db => shift->pg->db)
#        });
#       $app->helper(
#           v_sentinel_interface_list => sub {
#               state  $v_sentinel_interface_list = Daje::Database::Model::vSentinelInterfaceList->new(db => shift->pg->db)
#        });#
# DESCRIPTION
# ===========
#
# Daje::Plugin::Sentinel::Helpers is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-16 07:04:48.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-16 07:04:48 -->

use Daje::Database::View::vSentinelStatus;
use Daje::Database::View::vSentinelSentinel;
use Daje::Database::View::vSentinelCheckpointLog;
use Daje::Database::View::vSentinelSentinelActions;
use Daje::Database::View::vSentinelCheckpoint;
use Daje::Database::View::vSentinelInterface;# Lists
use Daje::Database::View::vSentinelStatusList;
use Daje::Database::View::vSentinelSentinelList;
use Daje::Database::View::vSentinelCheckpointLogList;
use Daje::Database::View::vSentinelSentinelActionsList;
use Daje::Database::View::vSentinelCheckpointList;
use Daje::Database::View::vSentinelInterfaceList;

our $VERSION = '0.01';

sub helpers($self, $app, $config) {

    $app->helper(
        v_sentinel_status => sub {
            state  $v_sentinel_status = Daje::Database::View::vSentinelStatus->new(db => shift->pg->db)
        });
    $app->helper(
        v_sentinel_sentinel => sub {
            state  $v_sentinel_sentinel = Daje::Database::View::vSentinelSentinel->new(db => shift->pg->db)
        });
    $app->helper(
        v_sentinel_checkpoint_log => sub {
            state  $v_sentinel_checkpoint_log = Daje::Database::View::vSentinelCheckpointLog->new(db => shift->pg->db)
        });
    $app->helper(
        v_sentinel_sentinel_actions => sub {
            state  $v_sentinel_sentinel_actions = Daje::Database::View::vSentinelSentinelActions->new(db => shift->pg->db)
        });
    $app->helper(
        v_sentinel_checkpoint => sub {
            state  $v_sentinel_checkpoint = Daje::Database::View::vSentinelCheckpoint->new(db => shift->pg->db)
        });
    $app->helper(
        v_sentinel_interface => sub {
            state  $v_sentinel_interface = Daje::Database::View::vSentinelInterface->new(db => shift->pg->db)
        });    # Lists
    $app->helper(
        v_sentinel_status_list => sub {
            state  $v_sentinel_status_list = Daje::Database::View::vSentinelStatusList->new(db => shift->pg->db)
        });
    $app->helper(
        v_sentinel_sentinel_list => sub {
            state  $v_sentinel_sentinel_list = Daje::Database::View::vSentinelSentinelList->new(db => shift->pg->db)
        });
    $app->helper(
        v_sentinel_checkpoint_log_list => sub {
            state  $v_sentinel_checkpoint_log_list = Daje::Database::View::vSentinelCheckpointLogList->new(db => shift->pg->db)
        });
    $app->helper(
        v_sentinel_sentinel_actions_list => sub {
            state  $v_sentinel_sentinel_actions_list = Daje::Database::View::vSentinelSentinelActionsList->new(db => shift->pg->db)
        });
    $app->helper(
        v_sentinel_checkpoint_list => sub {
            state  $v_sentinel_checkpoint_list = Daje::Database::View::vSentinelCheckpointList->new(db => shift->pg->db)
        });
    $app->helper(
        v_sentinel_interface_list => sub {
            state  $v_sentinel_interface_list = Daje::Database::View::vSentinelInterfaceList->new(db => shift->pg->db)
        });}

1;




#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Plugin::Sentinel::Helpers - Model class



=head1 SYNOPSIS


      use Daje::Plugin::Sentinel::Helpers;

      my $class = Daje::Plugin::Sentinel::Helpers->new();
      $app->helper(
          v_sentinel_status => sub {
              state  $v_sentinel_status = Daje::Database::Model::vSentinelStatus->new(db => shift->pg->db)
       });
      $app->helper(
          v_sentinel_sentinel => sub {
              state  $v_sentinel_sentinel = Daje::Database::Model::vSentinelSentinel->new(db => shift->pg->db)
       });
      $app->helper(
          v_sentinel_checkpoint_log => sub {
              state  $v_sentinel_checkpoint_log = Daje::Database::Model::vSentinelCheckpointLog->new(db => shift->pg->db)
       });
      $app->helper(
          v_sentinel_sentinel_actions => sub {
              state  $v_sentinel_sentinel_actions = Daje::Database::Model::vSentinelSentinelActions->new(db => shift->pg->db)
       });
      $app->helper(
          v_sentinel_checkpoint => sub {
              state  $v_sentinel_checkpoint = Daje::Database::Model::vSentinelCheckpoint->new(db => shift->pg->db)
       });
      $app->helper(
          v_sentinel_interface => sub {
              state  $v_sentinel_interface = Daje::Database::Model::vSentinelInterface->new(db => shift->pg->db)
       });#
      $app->helper(
          v_sentinel_status_list => sub {
              state  $v_sentinel_status_list = Daje::Database::Model::vSentinelStatusList->new(db => shift->pg->db)
       });
      $app->helper(
          v_sentinel_sentinel_list => sub {
              state  $v_sentinel_sentinel_list = Daje::Database::Model::vSentinelSentinelList->new(db => shift->pg->db)
       });
      $app->helper(
          v_sentinel_checkpoint_log_list => sub {
              state  $v_sentinel_checkpoint_log_list = Daje::Database::Model::vSentinelCheckpointLogList->new(db => shift->pg->db)
       });
      $app->helper(
          v_sentinel_sentinel_actions_list => sub {
              state  $v_sentinel_sentinel_actions_list = Daje::Database::Model::vSentinelSentinelActionsList->new(db => shift->pg->db)
       });
      $app->helper(
          v_sentinel_checkpoint_list => sub {
              state  $v_sentinel_checkpoint_list = Daje::Database::Model::vSentinelCheckpointList->new(db => shift->pg->db)
       });
      $app->helper(
          v_sentinel_interface_list => sub {
              state  $v_sentinel_interface_list = Daje::Database::Model::vSentinelInterfaceList->new(db => shift->pg->db)
       });#


=head1 DESCRIPTION


Daje::Plugin::Sentinel::Helpers is the standard routes



=head1 REQUIRES

L<Daje::Database::View::vSentinelInterfaceList> 

L<Daje::Database::View::vSentinelCheckpointList> 

L<Daje::Database::View::vSentinelSentinelActionsList> 

L<Daje::Database::View::vSentinelCheckpointLogList> 

L<Daje::Database::View::vSentinelSentinelList> 

L<Daje::Database::View::vSentinelStatusList> 

L<Daje::Database::View::vSentinelInterface> Lists

L<Daje::Database::View::vSentinelCheckpoint> 

L<Daje::Database::View::vSentinelSentinelActions> 

L<Daje::Database::View::vSentinelCheckpointLog> 

L<Daje::Database::View::vSentinelSentinel> 

L<Daje::Database::View::vSentinelStatus> 

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

