package Daje::Plugin::Sentinel::Helpers;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::Sentinel::Helpers - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Plugin::Sentinel::Helpers;
#
#       my $class = Daje::Plugin::Sentinel::Helpers->new();
#       $app->helper(
#           sentinel_status => sub {
#               state  $sentinel_status = Daje::Database::Model::SentinelStatus->new(db => shift->pg->db)
#        });
#       $app->helper(
#           sentinel_sentinel => sub {
#               state  $sentinel_sentinel = Daje::Database::Model::SentinelSentinel->new(db => shift->pg->db)
#        });
#       $app->helper(
#           sentinel_checkpoint => sub {
#               state  $sentinel_checkpoint = Daje::Database::Model::SentinelCheckpoint->new(db => shift->pg->db)
#        });
#       $app->helper(
#           sentinel_interface => sub {
#               state  $sentinel_interface = Daje::Database::Model::SentinelInterface->new(db => shift->pg->db)
#        });
#       $app->helper(
#           sentinel_checkpoint_log => sub {
#               state  $sentinel_checkpoint_log = Daje::Database::Model::SentinelCheckpointLog->new(db => shift->pg->db)
#        });
#       $app->helper(
#           sentinel_sentinel_actions => sub {
#               state  $sentinel_sentinel_actions = Daje::Database::Model::SentinelSentinelActions->new(db => shift->pg->db)
#        });#
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::Sentinel::Routes is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-05 16:42:33.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-05 16:42:33 -->

our $VERSION = '0.01';

sub helpers($self, $app, $config) {

    $app->helper(
        sentinel_status => sub {
            state  $sentinel_status = Daje::Database::Model::SentinelStatus->new(db => shift->pg->db)
        });
    $app->helper(
        sentinel_sentinel => sub {
            state  $sentinel_sentinel = Daje::Database::Model::SentinelSentinel->new(db => shift->pg->db)
        });
    $app->helper(
        sentinel_checkpoint => sub {
            state  $sentinel_checkpoint = Daje::Database::Model::SentinelCheckpoint->new(db => shift->pg->db)
        });
    $app->helper(
        sentinel_interface => sub {
            state  $sentinel_interface = Daje::Database::Model::SentinelInterface->new(db => shift->pg->db)
        });
    $app->helper(
        sentinel_checkpoint_log => sub {
            state  $sentinel_checkpoint_log = Daje::Database::Model::SentinelCheckpointLog->new(db => shift->pg->db)
        });
    $app->helper(
        sentinel_sentinel_actions => sub {
            state  $sentinel_sentinel_actions = Daje::Database::Model::SentinelSentinelActions->new(db => shift->pg->db)
        });
}

1;

#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Plugin::Sentinel::Helpers - Model class



=head1 SYNOPSIS


      use Daje::Plugin::Sentinel::Helpers;

      my $class = Daje::Plugin::Sentinel::Helpers->new();
      $app->helper(
          sentinel_status => sub {
              state  $sentinel_status = Daje::Database::Model::SentinelStatus->new(db => shift->pg->db)
       });
      $app->helper(
          sentinel_sentinel => sub {
              state  $sentinel_sentinel = Daje::Database::Model::SentinelSentinel->new(db => shift->pg->db)
       });
      $app->helper(
          sentinel_checkpoint => sub {
              state  $sentinel_checkpoint = Daje::Database::Model::SentinelCheckpoint->new(db => shift->pg->db)
       });
      $app->helper(
          sentinel_interface => sub {
              state  $sentinel_interface = Daje::Database::Model::SentinelInterface->new(db => shift->pg->db)
       });
      $app->helper(
          sentinel_checkpoint_log => sub {
              state  $sentinel_checkpoint_log = Daje::Database::Model::SentinelCheckpointLog->new(db => shift->pg->db)
       });
      $app->helper(
          sentinel_sentinel_actions => sub {
              state  $sentinel_sentinel_actions = Daje::Database::Model::SentinelSentinelActions->new(db => shift->pg->db)
       });#



=head1 DESCRIPTION


Daje::Plugin::Sentinel::Routes is the standard routes



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com



=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

