package Daje::Plugin::Sentinel::Routes;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::Sentinel::Routes - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Plugin::Sentinel::Routes;
#
#       my $class = Daje::Plugin::Sentinel::Routes->new();
#       $r->get('/sentinel/api/v1/status/:sentinel_status_pkey');
#       $r->get('/sentinel/api/v1/sentinel/:sentinel_sentinel_pkey');
#       $r->get('/sentinel/api/v1/sentinel_status/:sentinel_status_fkey');

       
#       $r->get('/sentinel/api/v1/checkpoint/:sentinel_checkpoint_pkey');
#       $r->get('/sentinel/api/v1/checkpoint_interface/:sentinel_interface_fkey');

       
#       $r->get('/sentinel/api/v1/interface/:sentinel_interface_pkey');
#       $r->get('/sentinel/api/v1/checkpoint_log/:sentinel_checkpoint_log_pkey');
#       $r->get('/sentinel/api/v1/checkpoint_log_checkpoint/:sentinel_checkpoint_fkey');

       
#       $r->get('/sentinel/api/v1/sentinel_actions/:sentinel_sentinel_actions_pkey');
#       $r->get('/sentinel/api/v1/sentinel_actions_sentinel/:sentinel_sentinel_fkey');

       #
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::Sentinel::Routes is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-08 18:04:18.
# It will be generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-08 18:04:18 -->

our $VERSION = '0.01';

sub routes($self, $app, $config) {
    my $r = $app->routes;
    $r->get('/sentinel/api/v1/status/:sentinel_status_pkey')->to('SentinelStatus#sentinel_status_pkey');
    $r->get('/sentinel/api/v1/sentinel/:sentinel_sentinel_pkey')->to('SentinelSentinel#sentinel_sentinel_pkey');
    $r->get('/sentinel/api/v1/sentinel_status/:sentinel_status_fkey')->to('SentinelSentinel#load_sentinel_status_fkey');
    $r->get('/sentinel/api/v1/checkpoint/:sentinel_checkpoint_pkey')->to('SentinelCheckpoint#sentinel_checkpoint_pkey');
    $r->get('/sentinel/api/v1/checkpoint_interface/:sentinel_interface_fkey')->to('SentinelCheckpoint#load_sentinel_interface_fkey');
    $r->get('/sentinel/api/v1/interface/:sentinel_interface_pkey')->to('SentinelInterface#sentinel_interface_pkey');
    $r->get('/sentinel/api/v1/checkpoint_log/:sentinel_checkpoint_log_pkey')->to('SentinelCheckpointLog#sentinel_checkpoint_log_pkey');
    $r->get('/sentinel/api/v1/checkpoint_log_checkpoint/:sentinel_checkpoint_fkey')->to('SentinelCheckpointLog#load_sentinel_checkpoint_fkey');
    $r->get('/sentinel/api/v1/sentinel_actions/:sentinel_sentinel_actions_pkey')->to('SentinelSentinelActions#sentinel_sentinel_actions_pkey');
    $r->get('/sentinel/api/v1/sentinel_actions_sentinel/:sentinel_sentinel_fkey')->to('SentinelSentinelActions#load_sentinel_sentinel_fkey');
}


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Plugin::Sentinel::Routes - Model class



=head1 SYNOPSIS


      use Daje::Plugin::Sentinel::Routes;

      my $class = Daje::Plugin::Sentinel::Routes->new();
      $r->get('/sentinel/api/v1/status/:sentinel_status_pkey');
      $r->get('/sentinel/api/v1/sentinel/:sentinel_sentinel_pkey');
      $r->get('/sentinel/api/v1/sentinel_status/:sentinel_status_fkey');


=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS

=head2 routes($self,

 routes($self,();


=cut

