package Daje::Plugin::Sentinel::Routes;
use Mojo::Base -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Plugin::Sentinel::Routes - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Plugin::Sentinel::Routes;
#
#       my $class = Daje::Plugin::Sentinel::Routes->new();
#       $r->get('/sentinel/api/v1/sentinel/:sentinel_sentinel_pkey');
#       $r->get('/sentinel/api/v1/sentinel_status/:sentinel_status_fkey');

       
#       $r->get('/sentinel/api/v1/checkpoint_log/:sentinel_checkpoint_log_pkey');
#       $r->get('/sentinel/api/v1/checkpoint_log_checkpoint/:sentinel_checkpoint_fkey');

       
#       $r->get('/sentinel/api/v1/sentinel_actions/:sentinel_sentinel_actions_pkey');
#       $r->get('/sentinel/api/v1/sentinel_actions_sentinel/:sentinel_sentinel_fkey');

       
#       $r->get('/sentinel/api/v1/checkpoint/:sentinel_checkpoint_pkey');
#       $r->get('/sentinel/api/v1/checkpoint_interface/:sentinel_interface_fkey');

       
#       $r->get('/sentinel/api/v1/interface/:sentinel_interface_pkey');
#       $r->get('/sentinel/api/v1/status/:sentinel_status_pkey');#
#
# DESCRIPTION
# ===========
#
# Daje::Plugin::Sentinel::Routes is the standard routes
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#

# This file is generated automatically by Daje Tools 2026-01-17 17:14:13.
# It will be generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-17 17:14:13 -->

our $VERSION = '0.01';

sub routes($self, $app, $config) {
    my $r = $app->routes;
    $r->get('/sentinel/api/v1/sentinel/:sentinel_sentinel_pkey')->to('SentinelSentinel#sentinel_sentinel_pkey');
    $r->get('/sentinel/api/v1/sentinel_status/:sentinel_status_fkey')->to('SentinelSentinel#load_sentinel_status_fkey');
    $r->get('/sentinel/api/v1/checkpoint_log/:sentinel_checkpoint_log_pkey')->to('SentinelCheckpointLog#sentinel_checkpoint_log_pkey');
    $r->get('/sentinel/api/v1/checkpoint_log_checkpoint/:sentinel_checkpoint_fkey')->to('SentinelCheckpointLog#load_sentinel_checkpoint_fkey');
    $r->get('/sentinel/api/v1/sentinel_actions/:sentinel_sentinel_actions_pkey')->to('SentinelSentinelActions#sentinel_sentinel_actions_pkey');
    $r->get('/sentinel/api/v1/sentinel_actions_sentinel/:sentinel_sentinel_fkey')->to('SentinelSentinelActions#load_sentinel_sentinel_fkey');
    $r->get('/sentinel/api/v1/checkpoint/:sentinel_checkpoint_pkey')->to('SentinelCheckpoint#sentinel_checkpoint_pkey');
    $r->get('/sentinel/api/v1/checkpoint_interface/:sentinel_interface_fkey')->to('SentinelCheckpoint#load_sentinel_interface_fkey');
    $r->get('/sentinel/api/v1/interface/:sentinel_interface_pkey')->to('SentinelInterface#sentinel_interface_pkey');
    $r->get('/sentinel/api/v1/status/:sentinel_status_pkey')->to('SentinelStatus#sentinel_status_pkey');

    $r->get('/sentinel/api/v1/sentinel_list_all/')->to('SentinelSentinelList#load_all_sentinel_sentinel');
    $r->get('/sentinel/api/v1/sentinel_status_list/:sentinel_status_fkey')->to('SentinelSentinel#load_list_sentinel_status_fkey');
    $r->get('/sentinel/api/v1/checkpoint_log_list_all/')->to('SentinelCheckpointLogList#load_all_sentinel_checkpoint_log');
    $r->get('/sentinel/api/v1/checkpoint_log_checkpoint_list/:sentinel_checkpoint_fkey')->to('SentinelCheckpointLog#load_list_sentinel_checkpoint_fkey');
    $r->get('/sentinel/api/v1/sentinel_actions_list_all/')->to('SentinelSentinelActionsList#load_all_sentinel_sentinel_actions');
    $r->get('/sentinel/api/v1/sentinel_actions_sentinel_list/:sentinel_sentinel_fkey')->to('SentinelSentinelActions#load_list_sentinel_sentinel_fkey');
    $r->get('/sentinel/api/v1/checkpoint_list_all/')->to('SentinelCheckpointList#load_all_sentinel_checkpoint');
    $r->get('/sentinel/api/v1/checkpoint_interface_list/:sentinel_interface_fkey')->to('SentinelCheckpoint#load_list_sentinel_interface_fkey');
    $r->get('/sentinel/api/v1/interface_list_all/')->to('SentinelInterfaceList#load_all_sentinel_interface');
    $r->get('/sentinel/api/v1/status_list_all/')->to('SentinelStatusList#load_all_sentinel_status');
}


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Plugin::Sentinel::Routes - Model class



=head1 SYNOPSIS


      use Daje::Plugin::Sentinel::Routes;

      my $class = Daje::Plugin::Sentinel::Routes->new();
      $r->get('/sentinel/api/v1/sentinel/:sentinel_sentinel_pkey');
      $r->get('/sentinel/api/v1/sentinel_status/:sentinel_status_fkey');


=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS

=head2 routes($self,

 routes($self,();


=cut

