package Daje::Controller::Sentinel::Super::SentinelCheckpointLogList;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Sentinel::Super::SentinelCheckpointLogList - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Sentinel::Super::vSentinelCheckpointLog##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Sentinel::Super::SentinelCheckpointLog is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-01-18 15:11:44.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-18 15:11:44 -->

our $VERSION = '0.01';

sub load_all_sentinel_checkpoint_log($self) {
    $self->app->log->debug('Daje::Controller::Super::SentinelCheckpointLogList::load_all_sentinel_checkpoint_log ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_sentinel_checkpoint_log_list->load_all_sentinel_checkpoint_log_p()->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::SentinelCheckpointLogList::load_all_sentinel_checkpoint_log ' . $err);
        $self->render
    });
}
sub load_list_sentinel_checkpoint_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::SentinelCheckpointLogList::load_listsentinel_checkpoint_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('sentinel_checkpoint_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_sentinel__list->sentinel_checkpoint_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::SentinelCheckpointLog::load_sentinel_checkpoint_fkey ' . $err);
        $self->render
    });
}
1;





#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Controller::Sentinel::Super::SentinelCheckpointLogList - Model class



=head1 SYNOPSIS


      use Daje::Controller::Sentinel::Super::vSentinelCheckpointLog##



=head1 DESCRIPTION


Daje::Controller::Sentinel::Super::SentinelCheckpointLog is a standard controller



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com

This file is generated automatically by Daje Tools 2026-01-18 15:11:44.
It will be re-generated by Daje Tools again.
<!-- Autogenerated file 2026-01-18 15:11:44 -->


=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

