package Daje::Controller::Sentinel::Super::SentinelCheckpoints;
use Mojo::Base 'Mojolicious::Controller', -base, -signatures;
use v5.42;

# NAME
# ====
#
# Daje::Controller::Super::Sentinel::SentinelCheckpoints - Model class
#
# SYNOPSIS
# ========
#
#       use Daje::Controller::Sentinel::Super::vSentinelCheckpoints##
#
# DESCRIPTION
# ===========
#
# Daje::Controller::Sentinel::Super::SentinelCheckpoints is a standard controller
#
# METHODS
# =======
#
#
# LICENSE
# =======
#
# Copyright (C) janeskil1525.
#
# This library is free software; you can redistribute it and/or modify
# it under the same terms as Perl itself.
#
# AUTHOR
# ======
#
# janeskil1525 E<lt>janeskil1525@gmail.com
#
# This file is generated automatically by Daje Tools 2026-01-19 18:46:38.
# It will be re-generated by Daje Tools again.
# <!-- Autogenerated file 2026-01-19 18:46:38 -->

our $VERSION = '0.01';

sub load_sentinel_checkpoints_pkey($self) {
    $self->app->log->debug('Daje::Controller::Super::SentinelCheckpoints::load_sentinel__fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $pkey = $self->param('sentinel_checkpoints_pkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_sentinel_checkpoints->load_sentinel_checkpoints_pkey_p($pkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::SentinelCheckpoints::load_sentinel_checkpoints_pkey ' . $err);
        $self->render
    });
}
sub load_sentinel_workflow_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::SentinelCheckpoints::load_sentinel_workflow_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('sentinel_workflow_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_sentinel_->sentinel_workflow_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::SentinelCheckpoints::load_sentinel_workflow_fkey ' . $err);
        $self->render
    });
}sub load_sentinel_checkpoint_fkey($self) {
    $self->app->log->debug('Daje::Controller::Super::SentinelCheckpoints::load_sentinel_checkpoint_fkey ');
    $self->render_later;
    my ($companies_pkey, $users_pkey) = $self->jwt->companies_users_pkey(
         $self->req->headers->header('X-Token-Check')
    );
    my $fkey = $self->param('sentinel_checkpoint_fkey');

    $self->app->log->debug($self->req->headers->header('X-Token-Check'));
    # my $setting = $self->param('setting');
    $self->v_sentinel_->sentinel_checkpoint_fkey_p($fkey)->then(sub($result) {
        $self->render(json => $result->{data});
    })->catch(sub($err) {
        $self->app->log->error('Daje::Controller::Super::SentinelCheckpoints::load_sentinel_checkpoint_fkey ' . $err);
        $self->render
    });
}
1;


#################### pod generated by Pod::Autopod - keep this line to make pod updates possible ####################

=head1 NAME


Daje::Controller::Super::Sentinel::SentinelCheckpoints - Model class



=head1 SYNOPSIS


      use Daje::Controller::Sentinel::Super::vSentinelCheckpoints##



=head1 DESCRIPTION


Daje::Controller::Sentinel::Super::SentinelCheckpoints is a standard controller



=head1 REQUIRES

L<v5.42> 

L<Mojo::Base> 


=head1 METHODS





=head1 AUTHOR


janeskil1525 E<lt>janeskil1525@gmail.com

This file is generated automatically by Daje Tools 2026-01-19 18:46:38.
It will be re-generated by Daje Tools again.
<!-- Autogenerated file 2026-01-19 18:46:38 -->


=head1 LICENSE


Copyright (C) janeskil1525.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.



=cut

